sudo: required

language: go
go:
 - 1.10.0

services:
  - docker

script:
 - go get github.com/tools/godep
 - godep get
 - go test -v ./...
 - CGO_ENABLED=0 GOOS=linux godep go build -a -installsuffix cgo -o Nemo .
 - docker build -t valentinnc/nemo .



